#!/bin/bash
#
# dewr is a development wrapper

IMAGE_NAME=$(basename $PWD)

dewr_build() {
  docker build -t $IMAGE_NAME -f ci/Dockerfile .
}

dewr_sh() {
  docker run -it -v $PWD:/opt/app --rm --net=host $IMAGE_NAME sh
}

dewr_test() {
  docker run -v $PWD:/opt/app --rm $IMAGE_NAME ci/test
}

case "$1" in
  build)
    dewr_build
    ;;
  sh)
    dewr_sh
    ;;
  test)
    dewr_test
    ;;
  *)
    cat <<EOF && exit 1
usage: dewr <command>

commands:
  build  build container
  sh     run shell in container
  test   run tests in container
EOF
esac
