#!/bin/bash
#
# dewr is a development wrapper

IMAGE_NAME=$(basename $PWD)

dewr_build() {
  docker build -f ci/Dockerfile -t $IMAGE_NAME .
}

dewr_run() {
  docker run -it -v $PWD:/opt/app --rm --net=host $IMAGE_NAME $@
}

dewr_test() {
  dewr_run ci/test
}

case "$1" in
  build)
    dewr_build
    ;;
  run)
    dewr_run
    ;;
  test)
    dewr_test
    ;;
  *)
    cat <<EOF && exit 1
usage: dewr <command>

commands:
  build  build container
  run    run container
  test   run tests in container
EOF
esac
